#!/bin/bash
if [ -e /private/var/containers/Bundle/Application ]
then
	find /private/var/containers/Bundle/Application/ -maxdepth 2 -name Filza.app -print0 | while IFS= read -r -d '' file; 
		do rm -rf $(dirname "$file"); 
	done
fi
