#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

if [ -f /User/Documents/uncleyeung/pingfang85_13 ];then
    echo "删除:/User/Documents/uncleyeung/pingfang85_13"
    rm -rf /User/Documents/uncleyeung/pingfang85_13
    echo "删除:完成"
fi
exit 0
