#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

if [ -f /User/Documents/uncleyeung/tsukushi ];then
    echo "删除:/User/Documents/uncleyeung/tsukushi"
    rm -rf /User/Documents/uncleyeung/tsukushi
    echo "删除:完成"
fi
exit 0
